# base
FROM python:3.9-slim-buster AS base
RUN apt-get update && apt-get install -y \
    gcc
ADD requirements.txt /app/
ADD ./requirements/ /app/requirements/
RUN pip install -r /app/requirements.txt


# test (server)
FROM base AS test-server
ADD . /app
ENV QUART_APP camus
ENV QUART_ENV development
RUN pip install -r /app/requirements/test.txt


# dev
FROM test-server AS dev
RUN apt-get update && apt-get install -y \
    vim
ENV QUART_ENV development
RUN pip install -r /app/requirements/dev.txt
